// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://okiqmvzouyhxxktmgabx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9raXFtdnpvdXloeHhrdG1nYWJ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYyMzQ3ODUsImV4cCI6MjA2MTgxMDc4NX0.E8czPH6e1COZKXAOU6FFLH-d6J1rYQOygPxDTaw1uQQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);